### ISSUE TITLE
Beim Deinstall alle angelegten Modul Daten löschen (oder komplett behalten)

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/bricky#11]
Bei der erneuten Installtion gibt es die vormals angelegten Module noch (nur ohne Modulname).

<img width="471" alt="image" src="https://user-images.githubusercontent.com/330516/45731189-9ad75980-bbd6-11e8-8a65-eeb72456767a.png">

**Comment by tbaddade** [comment]
> Beim Deinstall alle angelegten Modul Daten löschen (oder komplett behalten

Das ist eine Grundsatzfrage. 

Was mir dazu aber einfällt, dass beim deinstallieren oder deaktivieren geprüft werden müsste, ob ein BrickModul im Einsatz ist und dann den Vorgang abbricht. Ansonsten holt man sich Whoops.


> Bei der erneuten Installtion gibt es die vormals angelegten Module noch (nur ohne Modulname).

Kannst du dein Vorgehen genauer schildern. Bei mir erscheint in der Liste der korrekte Modulname.

Hinweis:
Den Modulnamen, den man auf der Brickyseite vergibt, wird für das Anlegen des Core-Moduls genutzt und wird danach in der Brick Tabelle geleert. In der Übersichtsliste sollte daher immer der eigentliche Core-Modulname erscheinen.

**Comment by olien** [comment]
Zu 1.

Dafür hast Du ja ein neues Issue aufgemacht.


Zu 2.

Addon deaktivieren
Addon deinstallieren

Addon installieren

Alle vorher angelegten Module sind noch da... (ohne Namen)

Alle Module (Bricks) löschen


Addon deaktivieren
Addon deinstallieren

Addon installieren


Modul installieren

Addon deaktivieren
Addon deinstallieren

Addon installieren


**Alle Module sind nich da. Korrekt mit Namen.**
