### ISSUE TITLE
Readme zu den einzelnen Elementen

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/bricky#13]
es wäre schön, wenn es zu den einzelnen Elementen die Möglichkeit geben würde eine zuäzliche Info einzublenden (ähnlich wie bei der Modulsammlung?)

<img width="303" alt="image" src="https://user-images.githubusercontent.com/330516/45931310-cb1f4f00-bf6c-11e8-80f0-dfe669a74eb4.png">

**Comment by tbaddade** [comment]
Ggf. auch Screenshots anzeigen

**Comment by olien** [comment]
Siehe auch #6
