### ISSUE TITLE
interne Namen festlegen, damit es keine Verwechselung mit den REDAXO-Namen gibt

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/bricky#15]
Ich schreibe mal drauf los was aktuell so gibt

| Name | Beschreibung |
| - | - |
| Bricky | AddOnname |
| Brick | Ein Baustein/Element welches man dem Modul zuführen kann (Headline, Image etc.) | 
| Ctypes | Sind bei Bricky die Tabs bzw. deren Inhalte (könnten theoretisch auch anders als Tabs dargestellt werden) |
| Darstellung Normal | Alle Bricks/Bausteine sind in einem MBlock zu sehen |
| Darstellung Slices | Man wählt zuvor für den MBlock einen Brick/Baustein aus. Man erhält somit ein Modul, welches vom Prinzip wie ein REDAXO-Artikel mit Slices arbeitet |
| Grid | Raster, Auswahl der Spalten und deren Breiten | 
| Modul | normales REDAXO Modul, welches bei Bricky aber über die AddOn-Seite gepflegt wird. |

Sollten sich die Namen ändern, sollten wir auch die Variablen im Code anpassen.

**Comment by olien** [comment]
Infos in die Doku übernommen und können dort erweitert werden
