### ISSUE TITLE
Grid Auswahl

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/bricky#2]
Beim Anlegen eines Moduls mit auswählbar machen ob die Grid Auswahl eingebunden werden soll oder nicht...

<img width="654" alt="image" src="https://user-images.githubusercontent.com/330516/45711521-21b21500-bb8a-11e8-9803-15b1f53e5882.png">

**Comment by olien** [comment]
Erledigt

**Comment by tbaddade** [comment]
Kannst du den Commit dazu notieren?

**Comment by olien** [comment]
Auch das war schon möglich. Habe keinen eigenen Commit dafür
