### ISSUE TITLE
Values prüfen

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/bricky#20]
Wie kann ich ein Value prüfen?

```
if ($this->getVar('TEXT', '') != '') {
 // Anzeige
} else {
 // Hinweis
}
```

Hier werden ja auch die Bricks für die Ausgabe berücksichtig, die gar nicht "benutzt" werden.

**Comment by staabm** [comment]
REX_IS_VALUE `?

**Comment by olien** [comment]
Hm. Ich denke @tbaddade kann damit etwas anfangen. Das Problem ist, dass ich nicht wirklich auf empty prüfen kann.

**Comment by tbaddade** [comment]
wo genau soll willst du den Code einsetzen?

Vielleicht ist es auch schon das was du suchst

```
if ($this->getVar('TEXT', '') == '') {
    // Hinweis
} else if ($this->getVar('TEXT', '') != '') {
    // Anzeige
}
```

Die Hinweise sehe ich in den mitgelieferten Standard-Bricks eher nicht (die sollen so einfach wie möglich bleiben). Wenn man diese im Projekt benötigt, kann das Fragment kopieren und anpassen.

**Comment by olien** [comment]
Ich wollte mal zeigen, wie vielleicht das Feld für die Überschrift geprüft werden kann...

**Comment by tbaddade** [comment]
Vielleicht sollte man die Felder registrieren. Dann kann man auch vor der Ausgabe die Felder durchgehen und nicht registrierte rauswerfen.

**Comment by olien** [comment]
Hört sich gut an. Kannst Du ein kleines Beispiel erstellen?
