### ISSUE TITLE
Zwischenstand

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/bricky#23]
Ich denke wenn die Issues

#20
#19 (Beispiel f. Bootstrap und noch eines)

bearbeitet und 1,2,3 Beispielmodule dabei sind könnten wir eine Beta Version rausbringen.

Was meinst Du @tbaddade?

**Comment by tbaddade** [comment]
> Was meinst Du

Ich schau mir das zwischen den Tagen noch mal an. Aktuell wenig Zeit dazu.
Haben wir einen JS-Coder gefunden?

**Comment by olien** [comment]
nein

**Comment by olien** [comment]
mir fehlt auch noch ne idee für die ausgabe mit/in einem grid...

**Comment by olien** [comment]
#19 ist erledigt (könnte man evtl. "besser" lösen

**Comment by olien** [comment]
Done
