### ISSUE TITLE
'Module' umbennen?

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/bricky#24]
ggf. würde es sich anbieten, im Bricky umfeld nicht von 'modulen' zu sprechen, da dieser Begriff im redaxo context bereits belegt ist.

würde es sinn machen ggf. von 'bricks' o.ä. zu sprechen? (oder nen anderer nicht bereits belegter begriff?)

**Comment by olien** [comment]
Wäre für mich ok. Komme allerdings grad generell nicht weiter und "warte" auf Thomas :-)

**Comment by tbaddade** [comment]
@staabm In welchem Kontext ist dir das aufgefallen? Wenn von Module gesprochen wird, dann sollten das die REDAXO-Module sein.

Aus der Readme
> Module die Bricky nutzen, werden über Bricky selbst verwaltet. Das REDAXO-Modul wird automatisch erstellt und wird mit den sogenannten Bricks gefüttert.

**Comment by staabm** [comment]
Ich habe das addon installiert und die backend page dazu geöffnet.

Dann sehe ich dort eine liste von modulen. Dies fand ich verwirrend weil ich meine module normalerweise unter „module“ finde

**Comment by olien** [comment]
Hm. Das sind ja auch tatsächlich die von Bricky erstellten Module...

**Comment by staabm** [comment]
Vllt sollte man sie dann „Bricky-Module“ nennen. 

Aber war auch nur ein Vorschlag und kann gern abgebrochen werden

**Comment by olien** [comment]
Von mir aus gerne... @tbaddade ?

**Comment by tbaddade** [comment]
Mir wäre es egal. 

Als Info: Die Liste die dort erscheint, dass sind allesamt Core-Module. Nur wird eben die Moduleingabe über eine Art UI zusammengestellt und nicht über den üblichen Weg mit HTML und REX_VARs.
