### ISSUE TITLE
Reihenfolge im Select (Brick) beeinflussbar machen

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/bricky#26]
Hier wäre

- Überschrift
- Text

schöner

![image](https://user-images.githubusercontent.com/330516/50970485-c95ca580-14e1-11e9-9c9a-0bae907cf1e4.png)

**Comment by olien** [comment]
Evtl. Abhängig von der Reihenfolge in der boot.php?

![image](https://user-images.githubusercontent.com/330516/50970620-2a847900-14e2-11e9-9958-d0805632afe2.png)

**Comment by tbaddade** [comment]
Eventuell durch verschieben der Bricks im Brick-Modul?
Damit wäre die Reihenfolge auch von Modul zu Modul unterschiedlich.

**Comment by olien** [comment]
Könnte man machen. Finde ich gut die Idee!
