### ISSUE TITLE
Wie können eigene bricks einfach hinzugefügt werden?

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/bricky#27]
Müssen die alle immer in der boot.php eingetragen werden?

![image](https://user-images.githubusercontent.com/330516/50970664-4ee05580-14e2-11e9-98cc-2ae5b8562051.png)

**Comment by tbaddade** [comment]
Für mich ist das bereits die einfachste Variante. Hast du eine andere Idee?

**Comment by olien** [comment]
Und wie kann der Benutzer eigene Bricks hinzufügen (via Project / Theme Addon)?

**Comment by tbaddade** [comment]
> Und wie kann der Benutzer eigene Bricks hinzufügen

in der boot.php

```php
Bricky::getInstance()->addBrick(new Project\Brick\Element());
```

**Comment by olien** [comment]
Und wie könnte das im Theme Addon funktionieren? In der functions.php im inc Ordner?

**Comment by tbaddade** [comment]
> Und wie könnte das im Theme Addon funktionieren?

Das AddOn kenne ich nicht. Das müsste jemand anderes beantworten.

**Comment by olien** [comment]
Dann muß ich mal gucken. Ich hab das Project Addon nie benutzt (Theme kam nahezu zeitgleich und konnte "mehr"). Ist nicht wertend gemeint.

**Comment by olien** [comment]
@DanielWeitenauer kannst du mir einen tipp geben?

**Comment by DanielWeitenauer** [comment]
@olien Alles was sich im inc-Ordner des Themes befindet wird über die boot.php includet. Die functions.php im theme-Addon kannst du also wie die boot.php im project-Addon benutzen.

**Comment by olien** [comment]
Danke. Probiere ich...
