### ISSUE TITLE
Nicht mehr vorhandene Module schon in der Übersicht kennzeichnen

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/bricky#28]
![image](https://user-images.githubusercontent.com/330516/50971485-63bde880-14e4-11e9-87c1-b10befc1650e.png)

**Comment by tbaddade** [comment]
Sollte das Brick-Modul dann nicht gleich mit gelöscht werden?

**Comment by olien** [comment]
Das wäre sinnvoll
