### ISSUE TITLE
Javascript optimieren

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/bricky#37]
@tbaddade   Was soll verbessert werden?

**Comment by tbaddade** [comment]
Der gesamte JS-Code … Wer Lust und Zeit hat kann sehr gern einen PR erstellen.

**Comment by olien** [comment]
Also hauptsächlich das hier: 

https://github.com/FriendsOfREDAXO/bricky/blob/master/assets/bricky.js

**Comment by olien** [comment]
**Frage im Slack:**

Ist der JS-Code korrekt und es geht um semantische/optische Verbesserungen oder knirscht es noch an der ein oder anderen Stelle was die Funktion betrifft?

**Comment by olien** [comment]
wir brauchen noch jemand der sich für das JS verantwortlich fühlt … nicht nur der eventuelle Umbau sondern auch jemanden, der sich kümmert, sobald etwas neues gebraucht wird
