### ISSUE TITLE
Repo archivieren ?

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/bricky#38]
Da niemand weiter mithelfen mag, wäre ich dafür das Projekt einzustellen und das Repo zu archivieren.

Was meinst du @olien  ?

**Comment by olien** [comment]
Leider stimme ich Dir zu. Obwohl ich immer noch glaube, dass das AddOn die Arbeitsweise vieler positiv ändern würde und das Bricky REDAXO einen weiteren Schritt "nach vorne" gebracht hätte!!!

Das Modul welches ich nutze ist ein kleiner Pups im Vergleich zu Bricky :-(((

Ich denke das die Leute nicht verstanden haben was Bricky werden würde!

sniff....

**Comment by tbaddade** [comment]
Dann lassen wir es noch einige Zeit offen.

**Comment by skerbis** [comment]
Ich will ja ... habe aber kaum Zeit im Moment  ... außerdem ist das Thema in Slack gerade wieder heiß
