### ISSUE TITLE
Verschiebbare Tabs (Drag & Drop) realisieren

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/bricky#5]
<img width="704" alt="image" src="https://user-images.githubusercontent.com/330516/45711691-ab61e280-bb8a-11e8-94eb-3ee07f9caba6.png">

**Comment by olien** [comment]
Erledigt

**Comment by tbaddade** [comment]
Das sollte bereits möglich gewesen sein. Kannst du deinen Commit hier zu schreiben.

**Comment by olien** [comment]
ja. war schon möglich... deswegen kann es ja zu - habe keinen eigenen commit dazu

**Comment by tbaddade** [comment]
ah super
